import { Switch, Route } from "react-router-dom";
import DistributionSolver from "./DistributionSolver";
import MiddlemanSolver from "./MiddlemanSolver";
import styles from "./MainContent.module.css";

export const MainContent = () => {
  const stuff = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque metus sem, gravida eu eros ac, sagittis aliquet dui. Vivamus blandit turpis ante, nec laoreet mi pellentesque eget. Suspendisse finibus consectetur velit. Nullam gravida tellus a tortor imperdiet imperdiet. Aenean ut risus varius, venenatis leo id, dignissim turpis. Sed ultricies finibus lacus vel malesuada. Praesent vehicula sapien ultrices ex aliquet elementum. Mauris consectetur sodales ante eu dictum. Aliquam varius odio at lacus bibendum facilisis. Vivamus faucibus, leo non pretium congue, leo nunc placerat nunc, eu tempus metus mi vel lorem. Nullam hendrerit mi vel mollis ultrices. Nullam et ultrices ipsum.

    Sed a ante a lorem efficitur lobortis id ut ante. Phasellus sit amet sapien purus. Duis blandit justo in dui tristique, vitae lacinia lectus fringilla. Sed tempor tellus sapien, ut rhoncus urna posuere a. Aenean in elit eget purus lacinia elementum. Maecenas sit amet nibh et tellus accumsan egestas lobortis a risus. Morbi varius cursus nulla, eu ultrices justo interdum ut. Quisque ex augue, vehicula in congue at, egestas ut quam. Nulla leo tortor, dapibus nec gravida sit amet, egestas elementum est. Praesent risus purus, tincidunt eget finibus id, tempor vel lorem. Quisque imperdiet tellus nunc, id fermentum dui condimentum eget. Praesent nec magna et purus accumsan ullamcorper sit amet non dui. Phasellus sed lectus ac mauris dictum luctus. Aenean iaculis accumsan laoreet.
    
    Vivamus at nulla vehicula, tincidunt orci vel, aliquet ex. Duis ornare placerat eros, quis dictum tortor dignissim eget. Sed condimentum, turpis ac sodales molestie, est mauris dignissim magna, eget tincidunt libero turpis nec eros. Aliquam pellentesque, quam a efficitur vehicula, tellus enim gravida risus, id blandit ante sem non diam. Curabitur semper, ligula non commodo semper, ipsum eros egestas sem, eu cursus nunc magna vitae neque. Vivamus scelerisque risus eu turpis egestas, et malesuada magna semper. Nulla maximus, tortor sit amet condimentum viverra, justo eros rhoncus nisl, ac vehicula est turpis et nulla. Aliquam a justo nec metus dictum tristique. Maecenas nec nulla quis dolor varius convallis vel dignissim nulla. Fusce magna tellus, venenatis in urna vitae, maximus elementum arcu. Maecenas commodo ornare tristique.
    
    Ut ultricies blandit leo sit amet varius. Vestibulum sagittis lectus id justo elementum, nec venenatis augue placerat. Cras facilisis luctus euismod. Vivamus suscipit magna est, sit amet aliquam arcu volutpat eu. Sed venenatis sit amet ligula fringilla aliquam. Sed posuere arcu quis lacus fringilla, ac vulputate magna rutrum. Duis sodales faucibus magna, non posuere tortor ullamcorper non. In hac habitasse platea dictumst. Maecenas justo arcu, vehicula eu congue ut, faucibus non nisi. Duis aliquet elit nec tincidunt imperdiet. Integer nec sem diam.
    
    Nullam porta blandit ex eget rhoncus. Aenean sit amet placerat risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin consequat est id libero placerat, in pretium felis maximus. In diam lectus, ornare vitae vehicula sed, finibus nec nulla. Nunc nec luctus eros. Phasellus porttitor dolor mauris, ut finibus leo euismod eget. Morbi in vehicula ex. Curabitur ex felis, venenatis in libero finibus, scelerisque efficitur orci. Ut maximus eros vel felis cursus lacinia. Proin accumsan purus eu felis tristique, eu pretium metus blandit.
    
    Nam aliquet tristique diam nec consequat. Suspendisse fermentum vel lectus maximus facilisis. Curabitur convallis justo non metus lacinia ullamcorper. Cras lacinia arcu sit amet semper dignissim. Nunc finibus urna ac aliquam condimentum. Integer ornare tempor lorem, at pulvinar massa rutrum id. Nunc malesuada condimentum scelerisque. Praesent et ante risus.
    
    Morbi eu tincidunt velit, ac elementum diam. In feugiat tellus fringilla, bibendum massa vitae, semper orci. Morbi ultricies porttitor nisl eu aliquam. Donec volutpat, elit id tristique facilisis, dolor quam tempor sapien, ut feugiat sapien nisi at odio. Integer congue nulla id iaculis mollis. Vivamus ullamcorper non est at molestie. Suspendisse finibus dignissim suscipit. Vestibulum auctor ex quis elit ornare, dignissim pellentesque ipsum porta. Quisque vulputate congue dolor, eu venenatis nulla mollis id. Donec finibus quam id quam accumsan hendrerit. Morbi venenatis elementum ante, sit amet aliquam mauris. Praesent ac blandit eros. Donec faucibus, sem sit amet convallis tempus, leo mi accumsan neque, vel sodales sem nulla in felis. Morbi eget blandit odio. Phasellus non augue sollicitudin, fringilla lacus quis, consequat libero. Aliquam at magna pulvinar, laoreet leo nec, posuere odio.
    
    Mauris accumsan, est in sagittis sodales, sapien magna facilisis ipsum, non vulputate lacus augue id eros. Quisque tempor dui lectus, ut volutpat lorem cursus a. Pellentesque tristique sollicitudin est, non molestie urna tincidunt eget. Sed massa leo, ullamcorper eu feugiat sit amet, bibendum id neque. Curabitur purus orci, aliquam eu ligula eget, vulputate porta odio. Donec ac ligula blandit ipsum eleifend venenatis a non felis. Sed at nisl pretium, tincidunt erat eget, facilisis quam. Praesent nisl ipsum, convallis eget nisl non, varius consectetur est. Nullam convallis odio mollis, gravida ligula a, pharetra magna. Nunc ut felis efficitur, interdum felis ac, venenatis eros. Duis lobortis felis vitae imperdiet ultricies. Vestibulum feugiat efficitur mauris, id tincidunt eros auctor quis. Aliquam at sem eu metus elementum tincidunt. Nunc sodales commodo mauris. Proin accumsan arcu vitae tellus maximus iaculis. In convallis justo a metus efficitur, eget elementum ipsum accumsan.
    
    Quisque ornare pretium eros, quis rhoncus eros lobortis ut. Nunc et sem consequat, sodales leo non, blandit odio. Nullam vestibulum risus vitae rhoncus interdum. Aenean vel porttitor massa, a accumsan orci. Maecenas et purus ante. Aenean consequat dapibus quam, nec posuere ligula bibendum vel. Aliquam interdum orci et dui cursus tempor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis placerat risus eu lacus congue, a accumsan magna varius. Sed consectetur tortor posuere, rutrum odio eget, finibus felis. Nullam eu luctus felis. Donec leo magna, placerat non erat id, tempor porta ante.
    
    Aliquam augue elit, molestie eget ipsum ac, sagittis vehicula turpis. Vestibulum lorem orci, aliquam in massa at, consectetur vulputate metus. Duis et tortor felis. In fringilla, nibh sit amet tincidunt varius, dui odio pharetra libero, sed eleifend libero augue vehicula mi. Curabitur elementum ac urna eget dictum. Phasellus rhoncus odio risus, eu mollis mauris fermentum vitae. Nunc vulputate pulvinar fermentum.
    
    Integer viverra, erat sit amet tristique pellentesque, sapien orci vehicula massa, et mattis nibh arcu ac justo. Quisque eget ex dui. Aliquam pretium ligula nec diam dictum, interdum accumsan ligula imperdiet. Nam at lobortis ligula, sed dapibus ligula. Morbi commodo mattis urna, dapibus gravida enim eleifend iaculis. Morbi placerat dui sed metus imperdiet pellentesque. Donec dignissim, augue nec auctor placerat, dolor enim posuere ligula, ut interdum lectus risus vitae urna. Sed nec eleifend massa.
    
    In tristique dictum mauris nec tincidunt. Aliquam erat volutpat. Etiam sollicitudin porttitor maximus. Duis non sem facilisis, convallis odio in, posuere lorem. Vestibulum id ornare lorem. Suspendisse et convallis erat. Pellentesque ut rhoncus mauris. Nullam placerat interdum ligula, at ultrices odio egestas non. Morbi lobortis massa a egestas dignissim. Curabitur felis ante, tincidunt a bibendum vel, consequat ac lacus. Fusce aliquet efficitur consectetur. Cras velit nibh, rutrum vel urna sed, malesuada consectetur lorem. Nam in viverra metus, eu finibus tellus. Quisque dolor eros, dignissim ultrices velit vel, porta consectetur magna. Morbi ultrices turpis gravida ipsum scelerisque tincidunt. In lorem nibh, efficitur non purus sit amet, lacinia tempor nisi.
    
    Suspendisse vel condimentum quam. Curabitur tempor tincidunt massa, a gravida dui consequat at. Nam mollis turpis sagittis suscipit venenatis. Praesent varius commodo velit eu euismod. Proin pharetra nec massa a facilisis. Suspendisse imperdiet magna eget ante venenatis, lobortis cursus dolor malesuada. Aenean et tincidunt justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
    
    Ut porta est vitae tempus tincidunt. In vitae urna felis. Proin vulputate eget augue vitae rhoncus. In placerat leo ex, nec suscipit sem iaculis quis. Nam ullamcorper nunc sit amet mauris accumsan, vel blandit nunc egestas. Aliquam vestibulum eu lorem at faucibus. Mauris sed dolor lorem. Proin molestie molestie luctus. In lectus odio, bibendum nec metus sit amet, ornare sollicitudin sapien. Duis vitae vehicula turpis, id fringilla ex. Aliquam erat volutpat. Cras at libero eu orci pretium elementum eget consectetur libero. Vivamus posuere metus sollicitudin lectus consectetur, at dignissim dolor iaculis.
    
    Donec consequat facilisis nulla, non mollis massa gravida ac. Donec in nisi metus. Sed mattis nec lacus ut rhoncus. Curabitur ut magna tortor. In nec magna eu tellus convallis viverra. Aliquam ipsum justo, tempor sollicitudin finibus ac, tincidunt id nisl. Nullam porta, massa sed pellentesque semper, dui leo fringilla lectus, sed bibendum est est a ex. Donec massa est, semper et mauris ut, egestas viverra purus. Nunc non massa facilisis, egestas nulla quis, aliquet est. Praesent molestie sit amet erat vel rhoncus. Vivamus feugiat est ac leo lobortis, sed dignissim purus fermentum. Integer nec maximus dolor.
    
    Suspendisse eget dignissim libero. Vestibulum vitae leo id libero vestibulum lobortis vel vitae mauris. Etiam posuere pretium ultricies. Aliquam at leo sit amet nisi aliquam aliquet. Suspendisse et porta odio. In hac habitasse platea dictumst. Aenean interdum tortor et ex tincidunt eleifend. Morbi tincidunt velit non tincidunt suscipit. Curabitur aliquam mattis finibus. Quisque euismod porttitor tempus. In ultricies urna id metus maximus rutrum. Donec eleifend sagittis sem, a laoreet ante rhoncus sit amet.
    
    Pellentesque hendrerit imperdiet velit, sit amet ultrices nibh pharetra eu. Donec faucibus imperdiet nisi id auctor. Suspendisse sed dolor auctor, ultricies elit in, ornare eros. Maecenas scelerisque nunc eu diam imperdiet pretium sit amet ac orci. Quisque non euismod velit. Nulla faucibus orci a ante fermentum, ut tempor justo volutpat. Mauris et tempor justo. Mauris et ultrices velit. Vestibulum in mauris nulla. Nullam turpis metus, elementum id risus id, aliquet vulputate dui. Cras viverra pharetra tortor. Curabitur in ante dui. Duis faucibus justo quis quam tempus pharetra.
    
    Sed nulla tellus, laoreet ut eleifend ut, ornare non mauris. Fusce maximus diam odio, non efficitur enim egestas nec. Phasellus cursus, ex eu semper scelerisque, mi augue gravida velit, ac fringilla lorem felis eu dui. Ut commodo ante vitae urna posuere, non iaculis est volutpat. Aliquam in dui ornare massa laoreet tempus eget lobortis massa. Quisque a mi dui. Suspendisse nulla lectus, facilisis ac aliquet ut, consequat non dui. Integer tempus congue mi, vitae malesuada est feugiat at. Suspendisse in posuere eros, quis porta lorem. Integer a lectus dolor. Sed quis porta tortor.
     `;
  return (
    <Switch>
      <div className={`${styles["main-content"]} ${styles["align"]}`}>
        <div className={styles["align-item"]}>
          <Route path="/MiddlemanSolver">
            <MiddlemanSolver />
          </Route>
          <Route path="/DistributionSolver">
            <DistributionSolver />
          </Route>
          <Route exact path="/">
            <div>{stuff}</div>
          </Route>
        </div>
      </div>
    </Switch>
  );
};
